package com.autoarkaive.autoarkaive;

import android.accessibilityservice.AccessibilityService;
import android.app.Notification;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.view.accessibility.AccessibilityNodeInfoCompat;
import android.util.Log;
import android.view.accessibility.AccessibilityEvent;
import android.view.accessibility.AccessibilityNodeInfo;
import com.autoarkaive.communications.CheckinRequest;
import com.autoarkaive.communications.ResultFailure;
import com.moba11y.androida11yutils.A11yNodeInfo;

/**
 * Service which controls the Arkaive app UI
 */
public class AAService extends AccessibilityService
{
	private final String TAG = "AAService";

	public static final int FOREGROUND_SERVICE_ID = 101;

	// enum used to keep track of the service's state, e.g. which UI screen is currently showing or whether or not there was an error
	enum State
	{
		IDLE,
		LOGIN_SCREEN,
		COURSE_SCREEN,
		CHECKIN_SCREEN,
		DONE,
		FAILED
	}

	private State state = State.IDLE;

	// stores failure message when in the FAILED state
	private String failureMessage = null;

	// stores current checkin when not in the IDLE state
	private CheckinRequest checkin;

	// thread which monitors the socket to the server, kicks off checkins, and reports the results back to the server
	private Thread controllerThread;

    public AAService()
    {
    	// for testing
		checkin = new CheckinRequest(0, 0, 0, "smit109@usc.edu", "xxxxxxxx", "Principles of Software Development", null, null);
		state = State.LOGIN_SCREEN;
    }

	@Override
	public int onStartCommand(Intent intent, int flags, int startId)
	{
		Notification notification = new Notification.Builder(this)
				.setContentTitle("AutoArkaive")
				.setContentText("Service Running")
				.setSmallIcon(R.drawable.ic_launcher_foreground)
				.build();
		startForeground(FOREGROUND_SERVICE_ID, notification);

		return START_STICKY;
	}

	@Override
	protected void onServiceConnected()
	{
		super.onServiceConnected();
		Log.d(TAG, "onServiceConnected() called");
	}

	@Override
	public void onDestroy()
	{
		super.onDestroy();
		Log.w(TAG, "Destroyed!");
		stopForeground(true);
	}

	@Override
	/**
	 * Called by Android whenever the UI is changed to update accessibility information.
	 * XML settings restrict this funciton to events generated by the Arkaive app.
	 */
    public void onAccessibilityEvent(AccessibilityEvent event)
    {
		Log.i(TAG, "Caught accessibility event: " + event.toString());

		switch (event.getEventType())
		{
			//On Gesture events print out the entire view heirarchy!
			case AccessibilityEvent.TYPE_GESTURE_DETECTION_START:
				Log.d(TAG, A11yNodeInfo.wrap(getRootInActiveWindow()).toViewHeirarchy());
				break;
			case AccessibilityEvent.TYPE_VIEW_CLICKED:
				Log.d(TAG, event.getSource().toString());
				break;
			case AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED:
				Log.d(TAG, A11yNodeInfo.wrap(event.getSource()).toViewHeirarchy());
				onScreenLoad(A11yNodeInfo.wrap(event.getSource()));
			default: {
				if (event.getSource() != null) {
					Log.d(TAG, A11yNodeInfo.wrap(event.getSource()).toViewHeirarchy());
				}
			}
		}
    }

	/**
	 * Processes the load of a new UI screen and moves the checkin process forward
	 * @param rootNode
	 */
	private void onScreenLoad(A11yNodeInfo rootNode)
	{
		if(rootNode.getChildCount() > 0) // wait for the app to add children
		{
			if(state == State.LOGIN_SCREEN)
			{
				Log.i(TAG, "Autofilling login info...");
				A11yNodeInfo layout = rootNode.getChild(0).getChild(0);

				A11yNodeInfo usernameText = layout.getChild(1);
				A11yNodeInfo passwordText = layout.getChild(2);
				A11yNodeInfo loginButton = layout.getChild(3);

				// type in login info
				Bundle usernameArgs = new Bundle();
				usernameArgs.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE, checkin.username);
				usernameText.getAccessibilityNodeInfoCompat().performAction(AccessibilityNodeInfo.ACTION_SET_TEXT, usernameArgs);

				Bundle passwordArgs = new Bundle();
				passwordArgs.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE, checkin.password);
				passwordText.getAccessibilityNodeInfoCompat().performAction(AccessibilityNodeInfo.ACTION_SET_TEXT, passwordArgs);

				// now, hit it!
				loginButton.performAction(A11yNodeInfo.Actions.CLICK);

				state = State.COURSE_SCREEN;
			}
			else if(state == State.COURSE_SCREEN)
			{

			}
		}
	}

    @Override
    public void onInterrupt()
	{
		// do nothing
	}

	// thread which monitors the socket to the server, kicks off checkins, and reports the results back to the server
	private class CheckinControllerThread
	{
		public void run()
		{
			try
			{
				switch(state)
				{
					case IDLE:
						// wait for next request from server

						// start Arkaive app

						state = State.LOGIN_SCREEN;
						break;

					case LOGIN_SCREEN:
					case COURSE_SCREEN:
					case CHECKIN_SCREEN:
						// spinlock until the UI actions have finished
						Thread.sleep(50);

						break;

					case DONE:
						// report success to server

						break;

					case FAILED:
						// report failure to server
						ResultFailure failureResult = new ResultFailure(failureMessage);

						break;
				}
			}
			catch(InterruptedException ex)
			{
				// do nothing
			}
		}
	}
}
